### ISSUE TITLE
Path gets lower-cased which breaks the redirect

### ISSUE THREAD

**Issue by clarkd** [wkallhof/Simple301#22]
When adding a new redirect, the URL/path is automatically lowercased which does not work for some systems.

For example, adding a redirect from /test to http://test.com/MyResource, results in the user being redirected to http://test.com/myresource (also shown in the UI).

**Comment by wkallhof** [comment]
@clarkd ,

This should be fixed in the latest v1.1.4 release : https://github.com/wkallhof/Simple301/commit/f1d2d0dd9ba900720bd96c4a440a6742228e7313

I have updated to not lower case external URLs

Thanks!

**Comment by clarkd** [comment]
Unfortunately it still looks like there's an issue, @wkallhof. It still gets lower-cased if the path isn't well formed (i.e. it's relative). Lines 70 and 119 of this RedirectRepository.cs.
